name: custom_ui_challenges
version: 0.1.0

environment:
  sdk: 3.1.0
  flutter: 3.13.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/
